# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
